apiVersion: v1
kind: Service
metadata:
  name: vault-service
  namespace: vault
spec:
  sessionAffinity: ClientIP
  type: NodePort
  selector:
    app: vault
  ports:
    - name: http
      protocol: TCP
      port: 8200
      nodePort: 30030
