apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs20gbvault
  namespace: vault
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs20gb
  nfs:
    server: k8s-infra-nfs
    path: /media/nfs/vault

