apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: vault
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      volumes:
      - name: vault-storage
        persistentVolumeClaim:
          claimName: vault-pvc-nfs20gb
      hostname: vault-pod
      containers:
        - name: vault
          image: hashicorp/vault:1.15.4
          securityContext:
            capabilities:
              add: ["IPC_LOCK"]
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
          - mountPath: "/vault"
            name: vault-storage
          env:
          - name: VAULT_ADDR
            value: 'http://vault-pod:8200'
          command: ["vault"]
          args: ["server", "-config=/vault/config", ""]
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /
              port: 8200
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 8200
            initialDelaySeconds: 35
            periodSeconds: 5
      nodeSelector:
        worker: "true"
